check_id: FV-D001-0001
dimension: ChargeType
check_friendly_name: "ChargeType must have a value from the list: {values}."
check:
  value_in:
    - "Adjustment"
    - "Purchase"
    - "Tax"
    - "Usage"
